apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ecommerce-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7004
          env:
            - name: PORT
              value: "7004"
            - name: DATABASE_URL
              value: "orders.db"
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: AMQP_URL
            - name: CATALOG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: CATALOG_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 7004
      targetPort: 7004
  selector:
    app: order-service
  type: ClusterIP
